upstream backend_servers {
    least_conn;   # or ip_hash or remove for round robin
    server backend1:8080;
    server backend2:8080;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend_servers;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Connection "";
    }
}
